name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version:
          # - 17
          # - 21
          - 24
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: 8.14.2

    - name: Build with Gradle
      run: gradle check koverXmlReport --no-daemon

    - name: Upload test results
      if: success() || failure() # always run even if the previous step fails
      uses: actions/upload-artifact@v4
      with:
        name: test-results-jdk-${{ matrix.java-version }}
        path: |
          **/build/reports/tests/
          **/build/test-results/

    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports-jdk-${{ matrix.java-version }}
        path: |
          **/build/reports/kover/

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-jdk-${{ matrix.java-version }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-jdk-${{ matrix.java-version }}-
